version: "3.9"
services:
  fastapi:
    build: ./api
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/app/models

  streamlit:
    build: ./app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - fastapi